Fixed -Wunterminated-string-initialization with GCC 15.
nginx/nginx pull request #134
Opened 2024-09-07 12:47 UTC by trofi

`gcc-15` added a new warning in https://gcc.gnu.org/PR115185:

    src/http/v2/ngx_http_v2_filter_module.c: In function
      'ngx_http_v2_header_filter':
    src/http/v2/ngx_http_v2_filter_module.c:118:36: error:
      initializer-string for array of 'unsigned char' is too long
        [-Werror=unterminated-string-initialization]
      118 |     static const u_char nginx[5] = "\x84\xaa\x63\x55\xe7";
          |                                    ^~~~~~~~~~~~~~~~~~~~~~
    src/http/v2/ngx_http_v2_filter_module.c:121:9: error:
      initializer-string for array of 'unsigned char' is too long
        [-Werror=unterminated-string-initialization]
      121 |         "\x8b\x84\x84\x2d\x69\x5b\x05\x44\x3c\x86\xaa\x6f";
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This change initializes the array bytewise to avoid string literal
assignnment (and avoid trailing "\0" truncation).

2024-09-09 13:15 UTC, arut commented
Seems like gcc-15 is in its early stages, so maybe it's too early to fix this. Generally I like the patch, just a couple of small comments. Plus the commit log should be in line with nginx standards, see https://github.com/nginx/nginx/blob/master/CONTRIBUTING.md.

2024-09-09 20:29 UTC, trofi commented
Reworded the commit message.

2024-09-26 15:03 UTC, pluknet requested changes
The commit misses the same issues in the QUIC code.

2024-09-26 21:50 UTC, trofi commented
Good point. Applied the similar change to `src/event/quic/ngx_event_quic_protection.c` as well.

2024-09-27 14:42 UTC, pluknet requested changes
Concerning the commit log.

We don't use multiple prefixes in the commit log.
If commit comes as a general fix touching unrelated places, the prefix is omitted.

Looking at the commit history to get similar commit messages, this leads to the next simple commit log:

Fixed -Wunterminated-string-initialization with GCC 15.

2024-09-27 14:42 UTC, pluknet commented on src/event/quic/ngx_event_quic_protection.c
> +    };
I don't think this is a change in the right direction.

What I'd like to see is declaring with unspecified array size, e.g. similar to the grpc module. This allows to keep using the initialization string unmodified, written in a more compact form, compared to a byte sequence.

Calculating the number of array elements with `sizeof() - 1` is a common approach used in nginx as well.

```
$ grep -E 'sizeof\([^)]+\) - 1' src/http/v2/ngx_http_v2_filter_module.c
    (ngx_http_v2_integer_octets(sizeof(h) - 1) + sizeof(h) - 1)
            len += 1 + sizeof(nginx) - 1;
            len += sizeof("; charset=") - 1 + r->headers_out.charset.len;
            location.len = sizeof("https://") - 1 + host.len
                location.len += sizeof(":65535") - 1;
            p = ngx_cpymem(location.data, "http", sizeof("http") - 1);
            len += 1 + sizeof(accept_encoding) - 1;
                                            sizeof(NGINX_VER) - 1, tmp);
                                            sizeof(NGINX_VER_BUILD) - 1, tmp);
            pos = ngx_cpymem(pos, nginx, sizeof(nginx) - 1);
            len = r->headers_out.content_type.len + sizeof("; charset=") - 1
            p = ngx_cpymem(p, "; charset=", sizeof("; charset=") - 1);
        len = sizeof("Wed, 31 Dec 1986 18:00:00 GMT") - 1;
        pos = ngx_cpymem(pos, accept_encoding, sizeof(accept_encoding) - 1);
```
 This covers both C arrays and literal strings.

As a bonus, this allows logging the `salt` value without variable length modifier:

```
@@ -152,8 +152,8 @@ ngx_quic_keys_set_initial_secret(ngx_quic_keys_t *keys, ngx_str_t *secret,
     ngx_log_debug0(NGX_LOG_DEBUG_EVENT, log, 0,
                    "quic ngx_quic_set_initial_secret");
 #ifdef NGX_QUIC_DEBUG_CRYPTO
-    ngx_log_debug3(NGX_LOG_DEBUG_EVENT, log, 0,
-                   "quic salt len:%uz %*xs", sizeof(salt), sizeof(salt), salt);
+    ngx_log_debug2(NGX_LOG_DEBUG_EVENT, log, 0,
+                   "quic salt len:%uz %xs", sizeof(salt) - 1, salt);
     ngx_log_debug3(NGX_LOG_DEBUG_EVENT, log, 0,
                    "quic initial secret len:%uz %*xs", is_len, is_len, is);
 #endif
```

2024-09-27 23:09 UTC, trofi commented
Switched `salt` to implicit array length, changed commit subject.

2024-09-29 01:48 UTC, pluknet commented
Please apply same in the rest places.
In the commit log, please remove compiler diagnostics, as it serves no purpose, and remove then to-be out-of-date bytewise statement.

2024-09-30 17:42 UTC, pluknet commented
On the other hand, removing explicit size from key_data and nonce may be error-prone, because they are passed without explicit size (the object size is implied by a selected cipher suite). And it could be a security issue, e.g. once NGX_QUIC_IV_LEN is enlarged.
On the other hand #2, key size and nonce size don't depend on a cipher, the lengths (and values) and statically defined in the spec.
So, it could be barely an issue if we would add a yet another QUIC version.

2024-11-29 17:10 UTC, closed without merging

2025-02-07 00:24 UTC, pgnd commented
@arut 

iiuc this was closed & not merged?
was this fixed elsewhere?

i hit it with current release + GCC15, as on Fedora 42+.  e.g.:

for Fedora41-release, with GCC14

@ https://gist.github.com/pgnd/23a3dd25ec9fe19d34f1b0850323d734#file-gistfile1-txt-L4900

```
...
 njs build dir: build
 njs CLI: build/njs

	chmod 755 blib/arch/auto/nginx/nginx.so
	make[2]: Entering directory '/builddir/build/BUILD/nginx-git_release_1.27.4-build/njs-master'
	/usr/bin/gcc -c -Isrc -Iexternal -Ibuild -pipe -fPIC -fvisibility=hidden -O -W -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wmissing-prototypes -Werror -g -fexcess-precision=standard -O -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -std=gnu17 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -std=gnu17 -Wno-deprecated-declarations \
		 \
		-o build/src/njs_diyfp.o \
		-MMD -MF build/src/njs_diyfp.dep -MT build/src/njs_diyfp.o \
		src/njs_diyfp.c
	Manifying 1 pod document
	make[2]: Leaving directory '/builddir/build/BUILD/nginx-git_release_1.27.4-build/nginx-nginx-005f01b/objs/src/http/modules/perl'
...
```

for Fedora42-prerelease, with GCC15

@ https://gist.github.com/pgnd/f40533deaea3f1defe82906bee25c77d#file-gistfile1-txt-L3669

```
...
 njs build dir: build
 njs CLI: build/njs

	make[2]: Entering directory '/builddir/build/BUILD/nginx-git_release_1.27.4-build/njs-master'
	/usr/bin/gcc -c -Isrc -Iexternal -Ibuild -pipe -fPIC -fvisibility=hidden -O -W -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wmissing-prototypes -Werror -g -fexcess-precision=standard -O -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -std=gnu17 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -std=gnu17 -Wno-deprecated-declarations \
		 \
		-o build/src/njs_diyfp.o \
		-MMD -MF build/src/njs_diyfp.dep -MT build/src/njs_diyfp.o \
		src/njs_diyfp.c
	In file included from src/njs_main.h:59,
	                 from src/njs_diyfp.c:12:
	src/njs_string.h: In function â€˜njs_string_encodeâ€™:
	src/njs_string.h:212:36: error: initializer-string for array of â€˜unsigned charâ€™ is too long [-Werror=unterminated-string-initialization]
	  212 |     static const u_char  hex[16] = "0123456789ABCDEF";
	      |                                    ^~~~~~~~~~~~~~~~~~
	cc1: all warnings being treated as errors
	make[2]: *** [build/Makefile:106: build/src/njs_diyfp.o] Error 1
	make[2]: Leaving directory '/builddir/build/BUILD/nginx-git_release_1.27.4-build/njs-master'
	make[1]: *** [objs/Makefile:1725: ../njs-master/nginx/../build/libnjs.a] Error 2
	make[1]: *** Waiting for unfinished jobs....
	make[1]: Leaving directory '/builddir/build/BUILD/nginx-git_release_1.27.4-build/nginx-nginx-005f01b'
	make: *** [Makefile:10: build] Error 2
	error: Bad exit status from /var/tmp/rpm-tmp.4GqmeD (%build)
...
```

2025-02-07 18:28 UTC, pluknet commented
Looks like it was closed as a coincidence.
If the issue continues to remain valid with the upcoming GCC 15 release (i.e. GCC developers won't back out this warning; at the time of writing, it is in stage 4, so there's still a change), I plan to get back to it to make nginx compilable.
Until then there is a workaround `./configure --with-cc-opt="-Wno-error=unterminated-string-initialization"`

2025-02-07 19:16 UTC, pgnd commented
> If the issue continues ... plan to get back to it to make nginx compilable.

got it, thx.

>  workaround

yup. the workaround works for now; GCC15 builds for F42 & Rawhide are good.

2025-02-07 22:18 UTC, trofi commented
It was closed because the scope of the fix kept growing without the sight of completion. The comments were too vague for me to clearly understand the desired end state.

After another merge conflict I gave up. It's just taking too much time from me to fix a trivial issue. I ended up disabling `-Werror` locally as well.

2025-02-11 18:41 UTC, ac000 commented
FWIW we hit the same issue in Unit.

For now we've disabled this warning until hopefully this [patch](https://gcc.gnu.org/pipermail/gcc-patches/2024-December/671714.html) (or similar) makes it into GCC then we can re-enable the warning and tag such arrays with the ["nonstring"](https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Common-Variable-Attributes.html) variable attribute.

2025-03-16 15:11 UTC, BwL1289 commented
FWIW `--with-cc-opt="-Wno-error=unterminated-string-initialization"` works for clang as well.

2025-03-16 16:19 UTC, ac000 commented
> FWIW `--with-cc-opt="-Wno-error=unterminated-string-initialization"` works for clang as well.

Hmm, which version of clang is that? AFAICT clang has no such option...

However seeing as the above mentioned patch has now been [merged](https://gcc.gnu.org/git/gitweb.cgi?p=gcc.git;h=622968990beee7499e951590258363545b4a3b57) into GCC 15 this issue can be handled properly...

2025-03-16 16:33 UTC, pgnd commented
@ac000 

> can be handled properly

do you have a link for that?

2025-03-16 22:06 UTC, ac000 commented
> @ac000
> 
> > can be handled properly
> 
> do you have a link for that?

The linked commit will allow `__attribute__(("nonstring"))` to silence this warning, e.g. you will be able to do

```c
static const char hex[16] __attribute__(("nonstring")) = "0123456789ABCDEF";
```

This will allow you to stick to defining string literals as `str[]` and character arrays as `str[N]`, with the difference of course being the `str[]` will be NUL terminated and the `str[N]` won't. This keeps the two use cases clearly defined.