Adding missing files from recent pcre2 library
nginx/nginx pull request #248
Opened 2024-10-09 07:20 UTC by thierryba

### Proposed changes

I tried to build nginx on windows with msvc. Everything went relatively well except it failed to link because of a missing symbol.
That symbol is defined in a missing file from the list of pcre2 sources.

2024-10-10 11:47 UTC, arut commented
Thanks for reporting this. This file was added recently. However we want to support old pcre2 versions as well. And there's another variable which should be used for files like this: `ngx_pcre_test`. Please try using that variable.

2024-10-10 12:51 UTC, thierryba commented
@arut thanks for pointing this out. I fixed the PR to use the right variable. I tested locally and it just works.

2024-10-15 13:50 UTC, pluknet requested changes
The patch looks good.

The commit message needs to be adjusted, it lacks a proper prefix and a trailing dot.
Also, it doesn't mention the specific PCRE library version the change aims to fix building with, nor that it is specific to MSVC.

Something like this should work:

```
Configure: MSVC compatibility with PCRE2 10.43.
```

Please force-push with the updated commit log, then I will approve&merge.

2024-10-15 13:58 UTC, thierryba commented
@pluknet thanks. Force-pushed.

2024-10-15 14:02 UTC, pluknet commented
pcre2_convert.c was added in PCRE2 10.43, not 10.44, so please record exactly this version in the commit log.
This may be useful later for archaeologic purposes.

2024-10-15 14:04 UTC, thierryba commented
@pluknet done.

2024-10-15 14:05 UTC, pluknet approved these changes

2024-10-15 14:18 UTC, merged