Core: implement TCP_KEEPALIVE on Darwin
nginx/nginx pull request #337
Opened 2024-11-19 15:24 UTC by panjf2000

### Proposed changes

In earlier versions, macOS only supported setting TCP_KEEPALIVE in place of TCP_KEEPIDLE, but macOS has supported TCP_KEEPINTVL and TCP_KEEPCNT since 10.8 in 2012.

Fixes #336

Ref:
https://lists.apple.com/archives/macnetworkprog/2012/Jul/msg00005.html 
https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/bsd/netinet/tcp.h#L215-L230 
https://github.com/apple-oss-distributions/xnu/blob/8d741a5de7ff4191bf97d57b9f54c2f6d4a15585/bsd/netinet/tcp.h#L226-L241

2024-12-12 13:16 UTC, panjf2000 commented
Kindly ping @arut @pluknet

2025-03-07 12:40 UTC, panjf2000 commented
> Kindly ping @arut @pluknet

@arut @pluknet

2025-03-21 00:46 UTC, panjf2000 commented
> > Kindly ping @arut @pluknet
> 
> @arut @pluknet

is anyone available?

2025-05-05 08:18 UTC, panjf2000 commented
Ping @pluknet @arut

2025-05-05 08:20 UTC, pluknet commented
I will look, thanks for reminder.

2025-05-16 09:31 UTC, panjf2000 commented
New reminder @pluknet

2025-05-16 15:16 UTC, pluknet commented
Actually, support first appeared in OS X Mavericks 10.9 (xnu-2422.1.72), then first documented in OS X Yosemite 10.10 (xnu-2782.1.97). See corresponding tags in https://github.com/apple-oss-distributions/xnu for tcp_usrreq.c and tcp.4 files.

Unfortunately, I cannot test if this actually works on OS X right now. Can you do this for me?
For example, check if "keepalive probes sent" counter is incremented in `netstat -s` according to the specified intervals.

2025-05-16 18:48 UTC, pluknet commented
After some testing on my old MBA, it appears that macOS doesn't inherit TCP socket options from listen socket.
Although it does seem copy them in the tcp_input routine (same as in ancient FreeBSD before syncache), this actually doesn't work and requires to set options on accepted socket.

2025-05-17 03:50 UTC, panjf2000 commented
> After some testing on my old MBA, it appears that macOS doesn't inherit TCP socket options from listen socket. Although it does seem copy them in the tcp_input routine (same as in ancient FreeBSD before syncache), this actually doesn't work and requires to set options on accepted socket.

You're right about this, please check out [this](https://github.com/nginx/nginx/pull/337#issue-2672554888).

2025-05-19 11:38 UTC, pluknet commented
>Core: optimize TCP keepalive and implement TCP_KEEPALIVE on Darwin

trailing dot please

> For TCP keepalive mechanism, `SO_KEEPALIVE` is inherited by a accepted
> socket from the listening socket on most UNIX-like OS's[^1], whereas
> `TCP_KEEP*` options are only inherited on Linux, FreeBSD,
> or DragonFlyBSD[^2] [^3] [^4] [^5] [^6] [^7] [^8]

please avoid introducing ugly github notation

> This PR does two things:
> 
> 1. Set TCP keepalive options on accepted sockets instead of the
> listening socket when the OS is not one of Linux, FreeBSD, or DragonFlyBSD.
> 
> 2. In earlier versions, macOS only supported setting `TCP_KEEPALIVE`
> in place of `TCP_KEEPIDLE`, but macOS has supported `TCP_KEEPINTVL`
> and `TCP_KEEPCNT` since 10.8 in 2012[^9] [^10] [^11]. Use `TCP_KEEPALIVE` on macOS.
> 
> Fixes #336

- It is not clear what "optimizes" in "optimize TCP keepalive" stands for.
- The change essentially adds support for Darwin.  I suggest concentrating exactly on this,
describing what the change does and why it is needed, i.e. what's the difference from other OSes.
- This is not a science article, citing 11 links is way too much, please limit to 1-2.

2025-05-19 12:13 UTC, pluknet requested changes

2025-05-19 12:13 UTC, pluknet commented on auto/unix
> +if [ -z "$NGX_HAVE_KEEPALIVE_TUNABLE" ]; then
This is supposed to test the feature in general way after testing it failed in a platform specific way.
I don't think this is needed at all, it is a waste of time.
Probably we just need to skip this generic test instead, see how this is done for kqueue().

2025-05-19 12:13 UTC, pluknet commented on src/core/ngx_connection.c
> +     defined(__linux__))
This would open-code and artificially limit the number of supported platforms.
Instead, I suggest introducing some darwin-specific macro and test accordingly.

2025-05-19 12:13 UTC, pluknet commented on src/core/ngx_connection.c
> +      */
As stated in the new Open Group specification,
it is implementation-defined which socket options on the accepted socket will have a default value determined by a value previously customized by setsockopt() on socket, rather than the default value used for other new sockets.

A better place for this kind of comment is in auto/os/darwin.
Something like:
: Darwin way to set TCP keepalive tunables, appeared in OS X Mavericks 10.9.
: Tunable values are set on the accepted socket.

2025-05-19 12:13 UTC, pluknet commented on src/event/ngx_event_accept.c
> +#endif
This introduces large code duplication, it should be factored out to a separate function.

2025-05-19 12:13 UTC, pluknet commented on src/event/ngx_event_accept.c
> +            if (setsockopt(s, IPPROTO_TCP, TCP_KEEPALIVE,
The code is clearly broken, sometimes it operates on "s", sometimes - on "ls->fd". 
Factorization should address this as well.

2025-05-19 12:29 UTC, panjf2000 commented on src/event/ngx_event_accept.c
> +#endif
Where should I put this function? src/event/ngx_event.c? or create a new src/event/ngx_event_tcp.c?

2025-05-22 12:15 UTC, panjf2000 commented on src/core/ngx_connection.c
> +     defined(__linux__))
For backward compatibility, we should continue to set keepalive on the listening socket and set these socket options on the accepted sockets for platforms other than dragonflybsd, freebsd and linux.

2025-05-26 22:12 UTC, pluknet reviewed
As further tested and looked though XNU sources,
it appears that only TCP_KEEPALIVE needs special attentions,
which allows to eliminate unneeded complexity in the change.

Since this can be rather a basic fix, it could land before the upcoming release.
To facilitate with the process, I made my own version, committed as 5b8a5c0.

See the commit log for details on TCP_KEEPALIVE.

Thanks for your initial work, I've put you in credits.

2025-05-26 22:12 UTC, pluknet commented on auto/sources
> +            src/event/ngx_event_tcp.c \
I don't think the added function deserves a whole new file,
it is either to put in platform-specific ngx_socket.c (due to ngx_socket_t parameter used),
or directly in ngx_connection.c, but see below.

2025-05-26 22:12 UTC, pluknet commented on src/core/ngx_connection.c
> +                          &ls[i].addr_text);
This way of passing of socket option values (and logging) doesn't give a clear clue what exactly might have failed.

2025-05-26 22:12 UTC, pluknet commented on src/event/ngx_event_accept.c
> +    !defined(__linux__)
As stated previous, this unnecessarily open-codes (limits) possible platforms for non-darwin case.
Instead you could test specifically for Darwin.

2025-05-26 22:12 UTC, pluknet commented on src/event/ngx_event_accept.c
> +     * TCP keepalive options are not inherited from the listening socket
wrong indentation

2025-05-26 22:13 UTC, closed without merging

2025-05-26 23:44 UTC, panjf2000 commented on src/event/ngx_event_accept.c
> +    !defined(__linux__)
Only these three OS's accepted sockets inherit `TCP_KEEP*` from the listening socket, so they don't need to go through the following code. I think it makes sense.

If we only check the darwin macro, some platforms might be missed, such as netbsd, solaris, etc. In other words, TCP keepalive won't be enabled on those platforms.